# Generated by Django 6.0.3 on 2026-04-13 09:09

from django.db import migrations, models


def mark_existing_messages_read(apps, schema_editor):
    ChatMessage = apps.get_model("core", "ChatMessage")
    for message in ChatMessage.objects.filter(read_at__isnull=True).only("id", "created_at"):
        message.read_at = message.created_at
        message.save(update_fields=["read_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_chatmessage_savedproperty"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_messages_read, migrations.RunPython.noop),
    ]
