# Generated by Django 6.0.3 on 2026-04-16 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid mobile number.",
                        regex="^\\+?[0-9]{10,15}$",
                    )
                ],
            ),
        ),
    ]
