# Generated by Django 6.0.3 on 2026-04-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_mobile_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                ],
                default="available",
                max_length=10,
            ),
        ),
    ]
