# Generated by Django 6.0.3 on 2026-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_property_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price_suffix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g., cr, lakh, k, etc.",
                max_length=20,
            ),
        ),
    ]
