# Generated by Django 6.0.3 on 2026-04-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_property_price_suffix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="price_suffix",
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.CharField(
                help_text="e.g., 1.3 cr, 25 lakh, 5k, ₹2500000", max_length=50
            ),
        ),
    ]
