# Generated by Django 6.0.5 on 2026-08-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cities/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Popular City",
                "verbose_name_plural": "Popular Cities",
                "ordering": ["order", "name"],
            },
        ),
    ]
