# Generated by Django 6.0.5 on 2026-08-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_popularcity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
