# Generated by Django 6.0.5 on 2026-09-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_user_avatar_user_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Urban Hunt", max_length=120)),
                (
                    "tagline",
                    models.CharField(
                        default="Better Homes, Brighter Tomorrows", max_length=255
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="rathodnikhil1107@gmail.com", max_length=254
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("allow_user_registration", models.BooleanField(default=True)),
                ("rent_enabled", models.BooleanField(default=True)),
                ("sell_enabled", models.BooleanField(default=True)),
                (
                    "default_property_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
            },
        ),
    ]
