# Generated by Django 6.0.5 on 2026-09-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_platformsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="allow_property_documents",
            field=models.BooleanField(default=True),
        ),
    ]
